<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>helloworld</groupId>
  <artifactId>javacard-applet</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <parent>
    <groupId>com.parent</groupId>
    <artifactId>javacard</artifactId>
    <version>1.0.0</version>
    <relativePath>./parent-javacard.xml</relativePath>
  </parent>

  <properties>
    <applet.id>01:02:03:04:05:06</applet.id>
    <applet.main.class>helloworld.HelloWorldApplet</applet.main.class>
    <applet.version>1.0</applet.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>io.github.git-commit-id</groupId>
        <artifactId>git-commit-id-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>io.github.svaningelgem</groupId>
        <artifactId>jacoco-console-reporter</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.klinec</groupId>
      <artifactId>jcardsim</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- This needs to be down here, because otherwise we get a classpath order conflict with
    jcardsim:
     `Invalid APDU loaded. You may have JC API in your classpath before JCardSim.` -->
    <dependency>
      <groupId>com.oracle.javacard</groupId>
      <artifactId>api-classic</artifactId>
    </dependency>
  </dependencies>
</project>
