name: Docker JavaCard CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Docker image
      run: |
        docker build --quiet --tag docker-javacard .
    - name: "Build Example: Ant"
      run: |
        docker run --rm --volume ./examples/ant/helloworld:/applet docker-javacard ant test applet
    - name: "Build Example: Gradle"
      run: |
        docker run --rm --volume ./examples/gradle/helloworld:/applet docker-javacard gradle clean buildJavaCard test
    - name: Change file ownership
      run: |
        sudo chown -R runner:runner ./examples/ant/helloworld/build/
        sudo chown -R runner:runner ./examples/gradle/helloworld/build/
    - name: Rename artifact files
      run: |
        mkdir -p ./artifacts/cap-files
        mv ./examples/ant/helloworld/build/helloworld.cap ./artifacts/cap-files/helloworld-ant.cap
        mv ./examples/gradle/helloworld/build/javacard/applet.cap ./artifacts/cap-files/helloworld-gradle.cap
    - name: Upload .cap files (JavaCard applets)
      uses: actions/upload-artifact@v4
      with:
        name: cap-files
        path: |
          ./artifacts/cap-files/
