name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push ant image
      uses: docker/build-push-action@v6
      with:
        file: ./docker/ant.Dockerfile
        context: .
        push: true
        tags: xoryouyou/javacard-ant:latest
        
    - name: Build and push gradle image
      uses: docker/build-push-action@v6
      with:
        file: ./docker/gradle.Dockerfile
        context: .
        push: true
        tags: xoryouyou/javacard-gradle:latest
