name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/ant.Dockerfile --tag javacard-ant:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file docker/gradle.Dockerifle --tag javacard-gradle:$(date +%s)
