name: Docker JavaCard CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build --quiet --tag docker-javacard .
    - name: "Build Example: Ant"
      run: |
        docker run --rm --env JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64 --volume ./examples/ant/helloworld:/applet docker-javacard ant test applet
    - name: Upload .cap files (JavaCard applets)
      uses: actions/upload-artifact@v4
      with:
        name: cap-files
        path: |
          examples/ant/helloworld/build/helloworld.cap
