name: Docker JavaCard CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Build Docker image
      run: |
        docker build --quiet --tag docker-javacard .
    - name: "Build Example: Ant"
      run: |
        docker run --rm --env JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64 --volume ./examples/ant/helloworld:/applet docker-javacard ant test applet
    - name: "Build Example: Gradle"
      run: |
        docker run --rm --env JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64 --volume ./examples/gradle/helloworld:/applet docker-javacard gradle clean buildJavaCard test
    - name: Generate GPG signing key
      env:
        OPENPGP_KEY_BIP39_MNEMONIC: ${{ secrets.OPENPGP_KEY_BIP39_MNEMONIC }}
      run: |
        curl -fsSL https://github.com/jpdarago/bip39key/releases/download/v1.5.2/bip39key-x86_64-unknown-linux-musl.tar.gz -o /tmp/bip39key.tar.gz
        echo "5c9e68a2eeb9456b61aadaacd5402119ab2065fa3046cdd95c93492c52038a4a  /tmp/bip39key.tar.gz" | sha256sum --check
        tar -xzf /tmp/bip39key.tar.gz -C /usr/local/bin/
        mv /usr/local/bin/bip39key-x86_64-unknown-linux-musl /usr/local/bin/bip39key
        echo "$OPENPGP_KEY_BIP39_MNEMONIC" | bip39key --user-id="JavaCard CI" --armor > ./maven-gpg-key.asc
        rm -f /tmp/bip39key.tar.gz
    - name: "Build Example: Maven"
      run: |
        docker run --rm \
          --volume ./maven-gpg-key.asc:/tmp/gpg-key.asc:ro \
          --volume .:/applet \
          --workdir /applet/examples/maven/helloworld \
          docker-javacard \
          bash -c '
            gpg --batch --import /tmp/gpg-key.asc && \
            mvn --no-transfer-progress \
              -Djava.compiler.main.path=/usr/lib/jvm/temurin-8-jdk-amd64/bin/javac \
              -Psign "-Dgpg.key=JavaCard CI" \
              clean verify
          '
    - name: Change file ownership
      run: |
        sudo chown -R runner:runner ./examples/ant/helloworld/build/
        sudo chown -R runner:runner ./examples/gradle/helloworld/build/
        sudo chown -R runner:runner ./examples/maven/helloworld/target/
    - name: Rename artifact files
      run: |
        mkdir -p ./artifacts/cap-files
        mv ./examples/ant/helloworld/build/helloworld.cap ./artifacts/cap-files/helloworld-ant.cap
        mv ./examples/gradle/helloworld/build/javacard/applet.cap ./artifacts/cap-files/helloworld-gradle.cap
        mv ./examples/maven/helloworld/target/010203040506.cap ./artifacts/cap-files/helloworld-maven.cap
        mv ./examples/maven/helloworld/target/010203040506.cap.asc ./artifacts/cap-files/helloworld-maven.cap.asc
        ls -lh ./artifacts/cap-files/
    - name: Upload .cap files (JavaCard applets)
      uses: actions/upload-artifact@v4
      with:
        name: cap-files
        path: |
          ./artifacts/cap-files/
  run-in-simulator:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Download Oracle JavaCard Simulator
      env:
        ORACLE_JAVACARD_SIMULATOR_URL: ${{ secrets.ORACLE_JAVACARD_SIMULATOR_URL }}
      run: |
        wget \
          --no-verbose \
          --output-document=./external/oracle_javacard_simulator/java_card_devkit_simulator-linux-bin-v25.0-b_474-23-APR-2025.tar.gz \
          "$ORACLE_JAVACARD_SIMULATOR_URL"
        echo "cc75856fd90ea8e2c30f3239cd70e6e259694a6679e81d0141940d8e5d083efd  ./external/oracle_javacard_simulator/java_card_devkit_simulator-linux-bin-v25.0-b_474-23-APR-2025.tar.gz" | sha256sum --check
    - name: Build Docker image
      run: |
        docker build --quiet --build-arg JAVACARD_SIMULATOR="java_card_devkit_simulator-linux-bin-v25.0-b_474-23-APR-2025.tar.gz" --tag docker-javacard .
    - uses: actions/download-artifact@v4
      with:
        name: cap-files
    - name: Run .cap file
      run: |
        docker run --rm \
          --volume ./helloworld-maven.cap:/applet/helloworld-maven.cap \
          --volume ./examples/maven/helloworld/hello.gpshell:/applet/hello.gpshell \
          --env START_JAVACARD_SIMULATOR=y \
          docker-javacard \
          bash -c 'gp() { java -jar /javacard/gp-v24.10.15.jar "$@"; } && unset GP_KEY GP_KEY_ENC GP_KEY_MAC GP_KEY_DEK && gp --install ./helloworld-maven.cap && gpshell ./hello.gpshell'
